
POST https://skjetlpadbmluieqcnlm.supabase.co/functions/v1/getemail 
Content-Type: application/json

{
  "email":"dhnaush@gmam",
  "pdfId":"fjjfjfjf"
}


###

GET http://13.127.225.252/api/setemail?pdfId=858b4eb3-caed-4437-a5e1-5f4cc771805b&email="jkgd@gmail.com"
Content-Type: application/json

{
  "id":"5113b108-c2b9-4aa4-851d-14a3ae6591a9"
}

###

GET http://localhost:3000/api/getpdf?id=62081777-f297-4f55-b84d-419fbfb3a27f
Content-Type: application/json

{
  "pdfId":"858b4eb3-caed-4437-a5e1-5f4cc771805b",
  "email":"jkgd@gmail.com",
  "data":"[{dd:dfhhf,ajajaj}]"
}

###


POST http://139.59.9.20:3000/api/createpdf
Content-Type: application/json

{
  "data" : {"personalDetail":{"firstName":"dhanush","lastName":"kamath","email":"dhanushkamath01@gmail.com","phoneNo":"+91919535434458","github":"https://github.com/dhanushkamathS","linkedin":"https://www.linkedin.com/in/dhanushkamaths/"},"experience":[{"company":"this & tha","role":"","location":"• This is a bullet point symbol.","date":"","points":[""]}],"education":[{"cllgName":"","course":"","location":"","year":""}],"projects":[{"projectName":"","tech":"","link":"","points":[""]}],"achievements":[{"name":"","points":[""]}],"skills":[]}
}